### PR TITLE
[release-v1.8] clustertask patch for devconsole create serverless function

### PR DESCRIPTION
**Pull request by Kaustubh-pande**
/cc @lance @dsimansk @jrangelramos

### CODE REVIEW

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by jrangelramos** [comment]
@Kaustubh-pande is the target branch correct?

**Comment by Kaustubh-pande** [comment]
Yes it is the correct branch for 1.29.

**Review by jrangelramos — APPROVED** [review]

**Pull request merged**
